### ISSUE TITLE
Is this likely to work in Linux/Ubuntu?

### ISSUE THREAD

**Issue by jradxl** [Jay-Rad/InstaTech_Server#1]
Hi,
Is this likely to work in Linux/Ubuntu with Mono or DotNetCore, using JetBeans Rider as the IDE?
Your HTTPS site is down
Kind Regards
John

**Comment by Manthan2611** [comment]
Hi John, 

I don't think that would work. As you required proper IIS Server installed. 

Regards,
Manthan

**Comment by bitbound** [comment]
@jradxl  Wow, am I late to the party.  Apparently I need to set up notifications on my projects.

@Manthan2611 is correct.  This project uses .NET Framework and requires an IIS on Windows.

However, I'm currently working on a new project that will combine the best parts of this and Adit (https://github.com/jay-rad/adit) into a cross-platform, .NET Core solution.  I'm a few months out from being able to release details on it, though.
